name: Spring Boot Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Give Maven Permission
        run: chmod +x mvnw

      - name: Build Spring Boot Project
        run: ./mvnw clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-build
          path: target/*.war
